<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Master\Unit;
use Carbon\Carbon;

class UnitSeeder extends Seeder
{
    public function run()
    {
        $units = [
            [
                'code' => 'CORPORATE',
                'name' => 'CORPORATE',
                'address' => 'Soekarno Hatta International Airport Building 600',
                'village' => 'Tangerang',
                'district' => 'Tangerang',
                'city' => 'Tangerang',
                'province' => 'Tangerang dan Banten',
                'country' => 'Indonesia',
                'phone' => '138',
                'fax' => '021-7805295',
                'mobile_phone' => '0856123456789',
                'email' => 'contact.center@angkasapura2.co.id',
                'description' => 'www.angkasapura2.co.id',
                'is_head_office' => 0,
                'lat' => null,
                'lon' => null,
                'is_active' => 1,
                'mst_unit_id' => 15,
                'created_by' => 1,
                'updated_by' => 1,
                'show_in_dashboard' => 0,
                'sorting' => 0
            ],
            [
                'code' => 'BTJ',
                'name' => 'KANTOR CABANG - BANDAR UDARA INTERNASIONAL SULTAN ISKANDAR MUDA (BTJ)',
                'address' => null,
                'village' => null,
                'district' => null,
                'city' => null,
                'province' => 'Banda Aceh',
                'country' => null,
                'phone' => null,
                'fax' => null,
                'mobile_phone' => null,
                'email' => 'contact.center@angkasapura2.co.id',
                'description' => '',
                'is_head_office' => 0,
                'lat' => 5.523522,
                'lon' => 95.420372,
                'is_active' => 1,
                'mst_unit_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'show_in_dashboard' => 1,
                'sorting' => 20
            ],
            [
                "code" => "KNO",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL KUALANAMU (KNO)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => 3.635499,
                "lon" => 98.87912,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 11
            ],
            [
                "code" => "PKU",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL SULTAN SYARIF KASIM II (PKU)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => 0.460786,
                "lon" => 101.444539,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 15
            ],
            [
                "code" => "TNJ",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL RAJA HAJI FISABILILLAH (TNJ)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => 0.922683,
                "lon" => 104.532311,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 21
            ],
            [
                "code" => "DJB",
                "name" => "KANTOR CABANG - BANDAR UDARA SULTAN THAHA (DJB)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -1.638016,
                "lon" => 103.644378,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 19
            ],
            [
                "code" => "PLM",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL SULTAN MAHMUD BADARUDDIN II (PLM)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -2.898249,
                "lon" => 104.699903,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 14
            ],
            [
                "code" => "PGK",
                "name" => "KANTOR CABANG - BANDAR UDARA DEPATI AMIR (PGK)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -2.162199,
                "lon" => 106.139064,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 18
            ],
            [
                "code" => "PDG",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL MINANGKABAU (PDG)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -0.7864,
                "lon" => 100.2837,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 17
            ],
            [
                "code" => "HLP",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL HALIM PERDANAKUSUMA (HLP)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -6.266607,
                "lon" => 106.891117,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 12
            ],
            [
                "code" => "BDO",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL HUSEIN SASTRANEGARA (BDO)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -6.903958,
                "lon" => 107.580161,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 13
            ],
            [
                "code" => "PNK",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL SUPADIO (PNK)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -0.15071,
                "lon" => 109.403892,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 16
            ],
            [
                "code" => "DTB",
                "name" => "KANTOR CABANG - BANDAR UDARA INTERNASIONAL SILANGIT (DTB)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => 2.259731,
                "lon" => 98.99185,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 22
            ],
            [
                "code" => "CGK",
                "name" => "KANTOR CABANG UTAMA - BANDAR UDARA INTERNASIONAL SOEKARNO HATTA (CGK)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "contact.center@angkasapura2.co.id",
                "description" => "",
                "is_head_office" => 0,
                "lat" => -5.762033,
                "lon" => 106.029053,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 10
            ],
            [
                "code" => "CEO",
                "name" => "CEO&#39;S OFFICE",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "info@agnkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => -5.61224,
                "lon" => 106.616996,
                "is_active" => 1,
                "ms_unit_id" => 15,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 1
            ],
            [
                "code" => "DE",
                "name" => "DIRECTOR OF ENGINEERING",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "info@angkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => -5.745962,
                "lon" => 106.613658,
                "is_active" => 1,
                "ms_unit_id" => 15,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 4
            ],
            [
                "code" => "DO",
                "name" => "DIRECTOR OF OPERATION &amp; SERVICE",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "info@angkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => null,
                "lon" => null,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 5
            ],
            [
                "code" => "DC",
                "name" => "DIRECTOR OF COMMERCIAL",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "info@angkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => null,
                "lon" => null,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 3
            ],
            [
                "code" => "DF",
                "name" => "DIRECTOR OF FINANCE",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "info@angkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => null,
                "lon" => null,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 6
            ],
            [
                "code" => "DH",
                "name" => "DIRECTOR OF HUMAN CAPITAL",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "info@angkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => null,
                "lon" => null,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 7
            ],
            [
                "code" => "BWX",
                "name" => "KANTOR CABANG - BANDAR UDARA BANYUWANGI (BWX)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "banyuwangi@angkasapura2.co.id",
                "description" => null,
                "is_head_office" => 0,
                "lat" => -8.219094,
                "lon" => 114.369142,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1708,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 23
            ],
            [
                "code" => "KJT",
                "name" => "KANTOR CABANG - BANDAR UDARA KERTAJATI (KJT)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "bandarakertajati@gmail.com",
                "description" => null,
                "is_head_office" => 0,
                "lat" => -5.585234,
                "lon" => 108.727727,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1974,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 24
            ],
            [
                "code" => "PKY",
                "name" => "KANTOR CABANG - BANDAR UDARA TJILIK RIWUT (PKY)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => "Palangkaraya",
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "palangkaraya@angkasapura2.co.id",
                "description" => null,
                "is_head_office" => 0,
                "lat" => -2.225,
                "lon" => 113.9425,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1974,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 25
            ],
            [
                "code" => "CSD",
                "name" => "COMMERCIAL SERVICE DIVISION (Directorat of Commercial)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "csd@gmail.com",
                "description" => null,
                "is_head_office" => 1,
                "lat" => null,
                "lon" => null,
                "is_active" => 1,
                "ms_unit_id" => 15,
                "created_by" => 1974,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 9
            ],
            [
                "code" => "ACD",
                "name" => "AIRPORT CONSTRUCTION DIVISION (Directorat of Engineering)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "OCD@GMAIL.COM",
                "description" => null,
                "is_head_office" => 1,
                "lat" => null,
                "lon" => null,
                "is_active" => 1,
                "ms_unit_id" => 15,
                "created_by" => 1974,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 8
            ],
            [
                "code" => "DS",
                "name" => "DIRECTOR OF TRANSFORMATION &amp; STRATEGIC PORTFOLIO",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "ds@angkasapura2.co.id",
                "description" => "www.angkasapura2.co.id",
                "is_head_office" => 1,
                "lat" => -5.745962,
                "lon" => 106.613658,
                "is_active" => 1,
                "ms_unit_id" => 15,
                "created_by" => 1708,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 2
            ],
            [
                "code" => "TKG",
                "name" => "KANTOR CABANG - BANDAR UDARA RADIN INTEN II (TKG)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => "Lampung",
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "radinintenII@angkasapura2.co.id",
                "description" => null,
                "is_head_office" => 0,
                "lat" => -5.2425,
                "lon" => 105.178889,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1708,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 26
            ],
            [
                "code" => "BKS",
                "name" => "KANTOR CABANG - BANDAR UDARA FATMAWATI SOEKARNO (BKS)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => null,
                "country" => "Bengkulu",
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "fatmawatibengkulu@angaksapura2.co.id",
                "description" => null,
                "is_head_office" => 0,
                "lat" => -3.861944,
                "lon" => 102.336667,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1708,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 27
            ],
            [
                "code" => "TJQ",
                "name" => "KANTOR CABANG - BANDAR UDARA H.A.S HANANDJOEDDIN (TJQ)",
                "address" => null,
                "village" => null,
                "district" => null,
                "city" => null,
                "province" => "Bangka Belutung",
                "country" => null,
                "phone" => null,
                "fax" => null,
                "mobile_phone" => null,
                "email" => "hanandjoeddin@angkasapura2.co.id",
                "description" => null,
                "is_head_office" => 0,
                "lat" => -2.745556,
                "lon" => 107.754722,
                "is_active" => 1,
                "ms_unit_id" => 1,
                "created_by" => 1708,
                "updated_by" => null,
                "show_in_dashboard" => 1,
                "sorting" => 28
            ]
        ];

        if (Unit::count() == 0) {
            Unit::insert($units);
        }        
    }
}
