<?php

namespace App\DTO\Worksheet;

use App\DTO\DTOContracts;
use InvalidArgumentException;

final class IdentificationRequestDTO implements DTOContracts
{
    public function __construct(
        public ?int $worksheet_id = null,
        public string $company_name,
        public string $company_code,
        public ?int $risk_category_t2_id = null,
        public ?int $risk_category_t3_id = null,
        public string $risk_chronology_body,
        public string $risk_chronology_description,

        public ?int $existing_control_type_id = null,
        public string $existing_control_body,
        public ?int $control_effectiveness_assessment_id = null,

        public string $risk_impact_category,
        public string $risk_impact_body,
        public string $risk_impact_start_date,
        public string $risk_impact_end_date,

        public string $inherent_body,
        public string $inherent_impact_value,
        public ?int $inherent_impact_scale_id = null,
        public int $inherent_impact_probability,
        public ?int $inherent_impact_probability_scale_id = null,
        public string $inherent_risk_exposure,
        public string $inherent_risk_level,
        public string $inherent_risk_scale,

        public string $residual_1_impact_value,
        public ?int $residual_1_impact_scale_id = null,
        public int $residual_1_impact_probability,
        public ?int $residual_1_impact_probability_scale_id = null,
        public string $residual_1_risk_exposure,
        public string $residual_1_risk_level,
        public string $residual_1_risk_scale,
        public string $residual_2_impact_value,
        public ?int $residual_2_impact_scale_id = null,
        public int $residual_2_impact_probability,
        public ?int $residual_2_impact_probability_scale_id = null,
        public string $residual_2_risk_exposure,
        public string $residual_2_risk_level,
        public string $residual_2_risk_scale,
        public string $residual_3_impact_value,
        public ?int $residual_3_impact_scale_id = null,
        public int $residual_3_impact_probability,
        public ?int $residual_3_impact_probability_scale_id = null,
        public string $residual_3_risk_exposure,
        public string $residual_3_risk_level,
        public string $residual_3_risk_scale,
        public string $residual_4_impact_value,
        public ?int $residual_4_impact_scale_id = null,
        public int $residual_4_impact_probability,
        public ?int $residual_4_impact_probability_scale_id = null,
        public string $residual_4_risk_exposure,
        public string $residual_4_risk_level,
        public string $residual_4_risk_scale
    ) {
        if (!in_array($this->risk_impact_category, ['kualitatif', 'kuantitatif'])) {
            throw new InvalidArgumentException('Risk Impact Category must be kualitatif or kuantitatif');
        }
    }

    public static function fromArray(array $data): self
    {
        return new self(
            worksheet_id: $data['worksheet_id'] ?? null,
            company_name: $data['company_name'] ?? '',
            company_code: $data['company_code'] ?? '',
            risk_category_t2_id: $data['risk_category_t2_id'] ?? null,
            risk_category_t3_id: $data['risk_category_t3_id'] ?? null,
            risk_chronology_body: $data['risk_chronology_body'] ?? '',
            risk_chronology_description: $data['risk_chronology_description'] ?? '',
            existing_control_type_id: $data['existing_control_type_id'] ?? null,
            existing_control_body: $data['existing_control_body'] ?? '',
            control_effectiveness_assessment_id: $data['control_effectiveness_assessment_id'] ?? null,
            risk_impact_category: $data['risk_impact_category'] ?? '',
            risk_impact_body: $data['risk_impact_body'] ?? '',
            risk_impact_start_date: $data['risk_impact_start_date'] ?? '',
            risk_impact_end_date: $data['risk_impact_end_date'] ?? '',
            inherent_body: $data['inherent_body'] ?? '',
            inherent_impact_value: $data['inherent_impact_value'] ?? '',
            inherent_impact_scale_id: $data['inherent_impact_scale_id'] ?? null,
            inherent_impact_probability: $data['inherent_impact_probability'] ?? 0,
            inherent_impact_probability_scale_id: $data['inherent_impact_probability_scale_id'] ?? null,
            inherent_risk_exposure: $data['inherent_risk_exposure'] ?? '',
            inherent_risk_level: $data['inherent_risk_level'] ?? '',
            inherent_risk_scale: $data['inherent_risk_scale'] ?? '',
            residual_1_impact_value: $data['residual_1_impact_value'] ?? '',
            residual_1_impact_scale_id: $data['residual_1_impact_scale_id'] ?? null,
            residual_1_impact_probability: $data['residual_1_impact_probability'] ?? 0,
            residual_1_impact_probability_scale_id: $data['residual_1_impact_probability_scale_id'] ?? null,
            residual_1_risk_exposure: $data['residual_1_risk_exposure'] ?? '',
            residual_1_risk_level: $data['residual_1_risk_level'] ?? '',
            residual_1_risk_scale: $data['residual_1_risk_scale'] ?? '',
            residual_2_impact_value: $data['residual_2_impact_value'] ?? '',
            residual_2_impact_scale_id: $data['residual_2_impact_scale_id'] ?? null,
            residual_2_impact_probability: $data['residual_2_impact_probability'] ?? 0,
            residual_2_impact_probability_scale_id: $data['residual_2_impact_probability_scale_id'] ?? null,
            residual_2_risk_exposure: $data['residual_2_risk_exposure'] ?? '',
            residual_2_risk_level: $data['residual_2_risk_level'] ?? '',
            residual_2_risk_scale: $data['residual_2_risk_scale'] ?? '',
            residual_3_impact_value: $data['residual_3_impact_value'] ?? '',
            residual_3_impact_scale_id: $data['residual_3_impact_scale_id'] ?? null,
            residual_3_impact_probability: $data['residual_3_impact_probability'] ?? 0,
            residual_3_impact_probability_scale_id: $data['residual_3_impact_probability_scale_id'] ?? null,
            residual_3_risk_exposure: $data['residual_3_risk_exposure'] ?? '',
            residual_3_risk_level: $data['residual_3_risk_level'] ?? '',
            residual_3_risk_scale: $data['residual_3_risk_scale'] ?? '',
            residual_4_impact_value: $data['residual_4_impact_value'] ?? '',
            residual_4_impact_scale_id: $data['residual_4_impact_scale_id'] ?? null,
            residual_4_impact_probability: $data['residual_4_impact_probability'] ?? 0,
            residual_4_impact_probability_scale_id: $data['residual_4_impact_probability_scale_id'] ?? null,
            residual_4_risk_exposure: $data['residual_4_risk_exposure'] ?? '',
            residual_4_risk_level: $data['residual_4_risk_level'] ?? '',
            residual_4_risk_scale: $data['residual_4_risk_scale'] ?? '',
        );
    }

    public function toArray(): array
    {
        return [
            'worksheet_id' => $this->worksheet_id,
            'company_name' => $this->company_name,
            'company_code' => $this->company_code,
            'risk_category_t2_id' => $this->risk_category_t2_id,
            'risk_category_t3_id' => $this->risk_category_t3_id,
            'risk_chronology_body' => $this->risk_chronology_body,
            'risk_chronology_description' => $this->risk_chronology_description,
            'existing_control_type_id' => $this->existing_control_type_id,
            'existing_control_body' => $this->existing_control_body,
            'control_effectiveness_assessment_id' => $this->control_effectiveness_assessment_id,
            'risk_impact_category' => $this->risk_impact_category,
            'risk_impact_body' => $this->risk_impact_body,
            'risk_impact_start_date' => $this->risk_impact_start_date,
            'risk_impact_end_date' => $this->risk_impact_end_date,
            'inherent_body' => $this->inherent_body,
            'inherent_impact_value' => $this->inherent_impact_value,
            'inherent_impact_scale_id' => $this->inherent_impact_scale_id,
            'inherent_impact_probability' => $this->inherent_impact_probability,
            'inherent_impact_probability_scale_id' => $this->inherent_impact_probability_scale_id,
            'inherent_risk_exposure' => $this->inherent_risk_exposure,
            'inherent_risk_level' => $this->inherent_risk_level,
            'inherent_risk_scale' => $this->inherent_risk_scale,
            'residual_1_impact_value' => $this->residual_1_impact_value,
            'residual_1_impact_scale_id' => $this->residual_1_impact_scale_id,
            'residual_1_impact_probability' => $this->residual_1_impact_probability,
            'residual_1_impact_probability_scale_id' => $this->residual_1_impact_probability_scale_id,
            'residual_1_risk_exposure' => $this->residual_1_risk_exposure,
            'residual_1_risk_level' => $this->residual_1_risk_level,
            'residual_1_risk_scale' => $this->residual_1_risk_scale,
            'residual_2_impact_value' => $this->residual_2_impact_value,
            'residual_2_impact_scale_id' => $this->residual_2_impact_scale_id,
            'residual_2_impact_probability' => $this->residual_2_impact_probability,
            'residual_2_impact_probability_scale_id' => $this->residual_2_impact_probability_scale_id,
            'residual_2_risk_exposure' => $this->residual_2_risk_exposure,
            'residual_2_risk_level' => $this->residual_2_risk_level,
            'residual_2_risk_scale' => $this->residual_2_risk_scale,
            'residual_3_impact_value' => $this->residual_3_impact_value,
            'residual_3_impact_scale_id' => $this->residual_3_impact_scale_id,
            'residual_3_impact_probability' => $this->residual_3_impact_probability,
            'residual_3_impact_probability_scale_id' => $this->residual_3_impact_probability_scale_id,
            'residual_3_risk_exposure' => $this->residual_3_risk_exposure,
            'residual_3_risk_level' => $this->residual_3_risk_level,
            'residual_3_risk_scale' => $this->residual_3_risk_scale,
            'residual_4_impact_value' => $this->residual_4_impact_value,
            'residual_4_impact_scale_id' => $this->residual_4_impact_scale_id,
            'residual_4_impact_probability' => $this->residual_4_impact_probability,
            'residual_4_impact_probability_scale_id' => $this->residual_4_impact_probability_scale_id,
            'residual_4_risk_exposure' => $this->residual_4_risk_exposure,
            'residual_4_risk_level' => $this->residual_4_risk_level,
            'residual_4_risk_scale' => $this->residual_4_risk_scale
        ];
    }
}
